//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.06 at 11:11:25 PM MSK 
//


package schemabindings31._int.icao.iwxxm._3;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;

import schemabindings31.net.opengis.gml.v_3_2_1.AbstractGMLType;


/**
 * <p>Java class for MeteorologicalAerodromeObservationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeteorologicalAerodromeObservationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractGMLType">
 *       &lt;sequence>
 *         &lt;element name="airTemperature" type="{http://icao.int/iwxxm/3.0}MeasureWithNilReasonType"/>
 *         &lt;element name="dewpointTemperature" type="{http://icao.int/iwxxm/3.0}MeasureWithNilReasonType"/>
 *         &lt;element name="qnh" type="{http://icao.int/iwxxm/3.0}MeasureWithNilReasonType"/>
 *         &lt;element name="surfaceWind">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://icao.int/iwxxm/3.0}AerodromeSurfaceWindPropertyType">
 *                 &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonType" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="visibility" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://icao.int/iwxxm/3.0}AerodromeHorizontalVisibilityPropertyType">
 *                 &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonType" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="rvr" maxOccurs="4" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://icao.int/iwxxm/3.0}AerodromeRunwayVisualRangePropertyType">
 *                 &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonType" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="presentWeather" type="{http://icao.int/iwxxm/3.0}AerodromePresentWeatherType" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="cloud" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://icao.int/iwxxm/3.0}AerodromeCloudPropertyType">
 *                 &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonType" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="recentWeather" type="{http://icao.int/iwxxm/3.0}AerodromeRecentWeatherType" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="windShear" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://icao.int/iwxxm/3.0}AerodromeWindShearPropertyType">
 *                 &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonType" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="seaCondition" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://icao.int/iwxxm/3.0}AerodromeSeaConditionPropertyType">
 *                 &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonType" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="runwayState" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://icao.int/iwxxm/3.0}AerodromeRunwayStatePropertyType">
 *                 &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonType" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="extension" type="{http://icao.int/iwxxm/3.0}ExtensionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="cloudAndVisibilityOK" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeteorologicalAerodromeObservationType", propOrder = {
    "airTemperature",
    "dewpointTemperature",
    "qnh",
    "surfaceWind",
    "visibility",
    "rvr",
    "presentWeather",
    "cloud",
    "recentWeather",
    "windShear",
    "seaCondition",
    "runwayState",
    "extension"
})
public class MeteorologicalAerodromeObservationType
    extends AbstractGMLType
{

    @XmlElement(required = true, nillable = true)
    protected MeasureWithNilReasonType airTemperature;
    @XmlElement(required = true, nillable = true)
    protected MeasureWithNilReasonType dewpointTemperature;
    @XmlElement(required = true, nillable = true)
    protected MeasureWithNilReasonType qnh;
    @XmlElement(required = true, nillable = true)
    protected MeteorologicalAerodromeObservationType.SurfaceWind surfaceWind;
    @XmlElementRef(name = "visibility", namespace = "http://icao.int/iwxxm/3.0", type = JAXBElement.class, required = false)
    protected JAXBElement<MeteorologicalAerodromeObservationType.Visibility> visibility;
    @XmlElement(nillable = true)
    protected List<MeteorologicalAerodromeObservationType.Rvr> rvr;
    
    @XmlElement(nillable = true,required = false)
    protected List<AerodromePresentWeatherType> presentWeather;
    
    @XmlElementRef(name = "cloud", namespace = "http://icao.int/iwxxm/3.0", type = JAXBElement.class, required = false)
    protected JAXBElement<MeteorologicalAerodromeObservationType.Cloud> cloud;
    @XmlElement(nillable = true)
    protected List<AerodromeRecentWeatherType> recentWeather;
    @XmlElementRef(name = "windShear", namespace = "http://icao.int/iwxxm/3.0", type = JAXBElement.class, required = false)
    protected JAXBElement<MeteorologicalAerodromeObservationType.WindShear> windShear;
    @XmlElementRef(name = "seaCondition", namespace = "http://icao.int/iwxxm/3.0", type = JAXBElement.class, required = false)
    protected JAXBElement<MeteorologicalAerodromeObservationType.SeaCondition> seaCondition;
    @XmlElement(nillable = true)
    protected List<MeteorologicalAerodromeObservationType.RunwayState> runwayState;
    protected List<ExtensionType> extension;
    @XmlAttribute(name = "cloudAndVisibilityOK", required = true)
    protected boolean cloudAndVisibilityOK;

    /**
     * Gets the value of the airTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureWithNilReasonType }
     *     
     */
    public MeasureWithNilReasonType getAirTemperature() {
        return airTemperature;
    }

    /**
     * Sets the value of the airTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureWithNilReasonType }
     *     
     */
    public void setAirTemperature(MeasureWithNilReasonType value) {
        this.airTemperature = value;
    }

    public boolean isSetAirTemperature() {
        return (this.airTemperature!= null);
    }

    /**
     * Gets the value of the dewpointTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureWithNilReasonType }
     *     
     */
    public MeasureWithNilReasonType getDewpointTemperature() {
        return dewpointTemperature;
    }

    /**
     * Sets the value of the dewpointTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureWithNilReasonType }
     *     
     */
    public void setDewpointTemperature(MeasureWithNilReasonType value) {
        this.dewpointTemperature = value;
    }

    public boolean isSetDewpointTemperature() {
        return (this.dewpointTemperature!= null);
    }

    /**
     * Gets the value of the qnh property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureWithNilReasonType }
     *     
     */
    public MeasureWithNilReasonType getQnh() {
        return qnh;
    }

    /**
     * Sets the value of the qnh property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureWithNilReasonType }
     *     
     */
    public void setQnh(MeasureWithNilReasonType value) {
        this.qnh = value;
    }

    public boolean isSetQnh() {
        return (this.qnh!= null);
    }

    /**
     * Gets the value of the surfaceWind property.
     * 
     * @return
     *     possible object is
     *     {@link MeteorologicalAerodromeObservationType.SurfaceWind }
     *     
     */
    public MeteorologicalAerodromeObservationType.SurfaceWind getSurfaceWind() {
        return surfaceWind;
    }

    /**
     * Sets the value of the surfaceWind property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeteorologicalAerodromeObservationType.SurfaceWind }
     *     
     */
    public void setSurfaceWind(MeteorologicalAerodromeObservationType.SurfaceWind value) {
        this.surfaceWind = value;
    }

    public boolean isSetSurfaceWind() {
        return (this.surfaceWind!= null);
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MeteorologicalAerodromeObservationType.Visibility }{@code >}
     *     
     */
    public JAXBElement<MeteorologicalAerodromeObservationType.Visibility> getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MeteorologicalAerodromeObservationType.Visibility }{@code >}
     *     
     */
    public void setVisibility(JAXBElement<MeteorologicalAerodromeObservationType.Visibility> value) {
        this.visibility = value;
    }

    public boolean isSetVisibility() {
        return (this.visibility!= null);
    }

    /**
     * Gets the value of the rvr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rvr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRvr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeteorologicalAerodromeObservationType.Rvr }
     * 
     * 
     */
    public List<MeteorologicalAerodromeObservationType.Rvr> getRvr() {
        if (rvr == null) {
            rvr = new ArrayList<MeteorologicalAerodromeObservationType.Rvr>();
        }
        return this.rvr;
    }

    public boolean isSetRvr() {
        return ((this.rvr!= null)&&(!this.rvr.isEmpty()));
    }

    public void unsetRvr() {
        this.rvr = null;
    }

    /**
     * Gets the value of the presentWeather property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the presentWeather property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPresentWeather().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AerodromePresentWeatherType }
     * 
     * 
     */
    public List<AerodromePresentWeatherType> getPresentWeather() {
        if (presentWeather == null) {
            presentWeather = new ArrayList<AerodromePresentWeatherType>();
        }
        return this.presentWeather;
    }

    public boolean isSetPresentWeather() {
        return ((this.presentWeather!= null)&&(!this.presentWeather.isEmpty()));
    }

    public void unsetPresentWeather() {
        this.presentWeather = null;
    }

    /**
     * Gets the value of the cloud property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MeteorologicalAerodromeObservationType.Cloud }{@code >}
     *     
     */
    public JAXBElement<MeteorologicalAerodromeObservationType.Cloud> getCloud() {
        return cloud;
    }

    /**
     * Sets the value of the cloud property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MeteorologicalAerodromeObservationType.Cloud }{@code >}
     *     
     */
    public void setCloud(JAXBElement<MeteorologicalAerodromeObservationType.Cloud> value) {
        this.cloud = value;
    }

    public boolean isSetCloud() {
        return (this.cloud!= null);
    }

    /**
     * Gets the value of the recentWeather property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recentWeather property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecentWeather().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AerodromeRecentWeatherType }
     * 
     * 
     */
    public List<AerodromeRecentWeatherType> getRecentWeather() {
        if (recentWeather == null) {
            recentWeather = new ArrayList<AerodromeRecentWeatherType>();
        }
        return this.recentWeather;
    }

    public boolean isSetRecentWeather() {
        return ((this.recentWeather!= null)&&(!this.recentWeather.isEmpty()));
    }

    public void unsetRecentWeather() {
        this.recentWeather = null;
    }

    /**
     * Gets the value of the windShear property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MeteorologicalAerodromeObservationType.WindShear }{@code >}
     *     
     */
    public JAXBElement<MeteorologicalAerodromeObservationType.WindShear> getWindShear() {
        return windShear;
    }

    /**
     * Sets the value of the windShear property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MeteorologicalAerodromeObservationType.WindShear }{@code >}
     *     
     */
    public void setWindShear(JAXBElement<MeteorologicalAerodromeObservationType.WindShear> value) {
        this.windShear = value;
    }

    public boolean isSetWindShear() {
        return (this.windShear!= null);
    }

    /**
     * Gets the value of the seaCondition property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MeteorologicalAerodromeObservationType.SeaCondition }{@code >}
     *     
     */
    public JAXBElement<MeteorologicalAerodromeObservationType.SeaCondition> getSeaCondition() {
        return seaCondition;
    }

    /**
     * Sets the value of the seaCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MeteorologicalAerodromeObservationType.SeaCondition }{@code >}
     *     
     */
    public void setSeaCondition(JAXBElement<MeteorologicalAerodromeObservationType.SeaCondition> value) {
        this.seaCondition = value;
    }

    public boolean isSetSeaCondition() {
        return (this.seaCondition!= null);
    }

    /**
     * Gets the value of the runwayState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the runwayState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRunwayState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MeteorologicalAerodromeObservationType.RunwayState }
     * 
     * 
     */
    public List<MeteorologicalAerodromeObservationType.RunwayState> getRunwayState() {
        if (runwayState == null) {
            runwayState = new ArrayList<MeteorologicalAerodromeObservationType.RunwayState>();
        }
        return this.runwayState;
    }

    public boolean isSetRunwayState() {
        return ((this.runwayState!= null)&&(!this.runwayState.isEmpty()));
    }

    public void unsetRunwayState() {
        this.runwayState = null;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionType }
     * 
     * 
     */
    public List<ExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<ExtensionType>();
        }
        return this.extension;
    }

    public boolean isSetExtension() {
        return ((this.extension!= null)&&(!this.extension.isEmpty()));
    }

    public void unsetExtension() {
        this.extension = null;
    }

    /**
     * Gets the value of the cloudAndVisibilityOK property.
     * 
     */
    public boolean isCloudAndVisibilityOK() {
        return cloudAndVisibilityOK;
    }

    /**
     * Sets the value of the cloudAndVisibilityOK property.
     * 
     */
    public void setCloudAndVisibilityOK(boolean value) {
        this.cloudAndVisibilityOK = value;
    }

    public boolean isSetCloudAndVisibilityOK() {
        return true;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://icao.int/iwxxm/3.0}AerodromeCloudPropertyType">
     *       &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonType" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Cloud
        extends AerodromeCloudPropertyType
    {

        @XmlAttribute(name = "nilReason")
        protected List<String> nilReason;

        /**
         * Gets the value of the nilReason property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nilReason property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNilReason().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getNilReason() {
            if (nilReason == null) {
                nilReason = new ArrayList<String>();
            }
            return this.nilReason;
        }

        public boolean isSetNilReason() {
            return ((this.nilReason!= null)&&(!this.nilReason.isEmpty()));
        }

        public void unsetNilReason() {
            this.nilReason = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://icao.int/iwxxm/3.0}AerodromeRunwayStatePropertyType">
     *       &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonType" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RunwayState
        extends AerodromeRunwayStatePropertyType
    {

        @XmlAttribute(name = "nilReason")
        protected List<String> nilReason;

        /**
         * Gets the value of the nilReason property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nilReason property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNilReason().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getNilReason() {
            if (nilReason == null) {
                nilReason = new ArrayList<String>();
            }
            return this.nilReason;
        }

        public boolean isSetNilReason() {
            return ((this.nilReason!= null)&&(!this.nilReason.isEmpty()));
        }

        public void unsetNilReason() {
            this.nilReason = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://icao.int/iwxxm/3.0}AerodromeRunwayVisualRangePropertyType">
     *       &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonType" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Rvr
        extends AerodromeRunwayVisualRangePropertyType
    {

        @XmlAttribute(name = "nilReason")
        protected List<String> nilReason;

        /**
         * Gets the value of the nilReason property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nilReason property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNilReason().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getNilReason() {
            if (nilReason == null) {
                nilReason = new ArrayList<String>();
            }
            return this.nilReason;
        }

        public boolean isSetNilReason() {
            return ((this.nilReason!= null)&&(!this.nilReason.isEmpty()));
        }

        public void unsetNilReason() {
            this.nilReason = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://icao.int/iwxxm/3.0}AerodromeSeaConditionPropertyType">
     *       &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonType" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SeaCondition
        extends AerodromeSeaConditionPropertyType
    {

        @XmlAttribute(name = "nilReason")
        protected List<String> nilReason;

        /**
         * Gets the value of the nilReason property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nilReason property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNilReason().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getNilReason() {
            if (nilReason == null) {
                nilReason = new ArrayList<String>();
            }
            return this.nilReason;
        }

        public boolean isSetNilReason() {
            return ((this.nilReason!= null)&&(!this.nilReason.isEmpty()));
        }

        public void unsetNilReason() {
            this.nilReason = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://icao.int/iwxxm/3.0}AerodromeSurfaceWindPropertyType">
     *       &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonType" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SurfaceWind
        extends AerodromeSurfaceWindPropertyType
    {

        @XmlAttribute(name = "nilReason")
        protected List<String> nilReason;

        /**
         * Gets the value of the nilReason property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nilReason property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNilReason().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getNilReason() {
            if (nilReason == null) {
                nilReason = new ArrayList<String>();
            }
            return this.nilReason;
        }

        public boolean isSetNilReason() {
            return ((this.nilReason!= null)&&(!this.nilReason.isEmpty()));
        }

        public void unsetNilReason() {
            this.nilReason = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://icao.int/iwxxm/3.0}AerodromeHorizontalVisibilityPropertyType">
     *       &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonType" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Visibility
        extends AerodromeHorizontalVisibilityPropertyType
    {

        @XmlAttribute(name = "nilReason")
        protected List<String> nilReason;

        /**
         * Gets the value of the nilReason property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nilReason property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNilReason().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getNilReason() {
            if (nilReason == null) {
                nilReason = new ArrayList<String>();
            }
            return this.nilReason;
        }

        public boolean isSetNilReason() {
            return ((this.nilReason!= null)&&(!this.nilReason.isEmpty()));
        }

        public void unsetNilReason() {
            this.nilReason = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://icao.int/iwxxm/3.0}AerodromeWindShearPropertyType">
     *       &lt;attribute name="nilReason" type="{http://www.opengis.net/gml/3.2}NilReasonType" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class WindShear
        extends AerodromeWindShearPropertyType
    {

        @XmlAttribute(name = "nilReason")
        protected List<String> nilReason;

        /**
         * Gets the value of the nilReason property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the nilReason property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNilReason().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getNilReason() {
            if (nilReason == null) {
                nilReason = new ArrayList<String>();
            }
            return this.nilReason;
        }

        public boolean isSetNilReason() {
            return ((this.nilReason!= null)&&(!this.nilReason.isEmpty()));
        }

        public void unsetNilReason() {
            this.nilReason = null;
        }

    }

}
