//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.27 at 12:41:52 PM MSK 
//


package _int.icao.iwxxm._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import net.opengis.gml.v_3_2_1.TimeInstantPropertyType;
import net.opengis.om._2.OMObservationPropertyType;


/**
 * <p>Java class for TropicalCycloneAdvisoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TropicalCycloneAdvisoryType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://icao.int/iwxxm/2.1}ReportType">
 *       &lt;sequence>
 *         &lt;element name="issueTime" type="{http://www.opengis.net/gml/3.2}TimeInstantPropertyType"/>
 *         &lt;element name="issuingTropicalCycloneAdvisoryCentre" type="{http://icao.int/iwxxm/2.1}UnitPropertyType"/>
 *         &lt;element name="tropicalCycloneName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="advisoryNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="observation" type="{http://www.opengis.net/om/2.0}OM_ObservationPropertyType"/>
 *         &lt;element name="forecast" type="{http://www.opengis.net/om/2.0}OM_ObservationPropertyType" maxOccurs="4" minOccurs="4"/>
 *         &lt;element name="remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="expectedNextAdvisoryTime" type="{http://www.opengis.net/gml/3.2}TimeInstantPropertyType"/>
 *         &lt;element name="extension" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TropicalCycloneAdvisoryType", propOrder = {
    "issueTime",
    "issuingTropicalCycloneAdvisoryCentre",
    "tropicalCycloneName",
    "advisoryNumber",
    "observation",
    "forecast",
    "remarks",
    "expectedNextAdvisoryTime",
    "extension"
})
public class TropicalCycloneAdvisoryType
    extends ReportType
{

    @XmlElement(required = true)
    protected TimeInstantPropertyType issueTime;
    @XmlElement(required = true)
    protected UnitPropertyType issuingTropicalCycloneAdvisoryCentre;
    @XmlElement(required = true)
    protected String tropicalCycloneName;
    protected int advisoryNumber;
    @XmlElement(required = true)
    protected OMObservationPropertyType observation;
    @XmlElement(required = true)
    protected List<OMObservationPropertyType> forecast;
    protected String remarks;
    @XmlElement(required = true, nillable = true)
    protected TimeInstantPropertyType expectedNextAdvisoryTime;
    protected List<Object> extension;

    /**
     * Gets the value of the issueTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeInstantPropertyType }
     *     
     */
    public TimeInstantPropertyType getIssueTime() {
        return issueTime;
    }

    /**
     * Sets the value of the issueTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeInstantPropertyType }
     *     
     */
    public void setIssueTime(TimeInstantPropertyType value) {
        this.issueTime = value;
    }

    public boolean isSetIssueTime() {
        return (this.issueTime!= null);
    }

    /**
     * Gets the value of the issuingTropicalCycloneAdvisoryCentre property.
     * 
     * @return
     *     possible object is
     *     {@link UnitPropertyType }
     *     
     */
    public UnitPropertyType getIssuingTropicalCycloneAdvisoryCentre() {
        return issuingTropicalCycloneAdvisoryCentre;
    }

    /**
     * Sets the value of the issuingTropicalCycloneAdvisoryCentre property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitPropertyType }
     *     
     */
    public void setIssuingTropicalCycloneAdvisoryCentre(UnitPropertyType value) {
        this.issuingTropicalCycloneAdvisoryCentre = value;
    }

    public boolean isSetIssuingTropicalCycloneAdvisoryCentre() {
        return (this.issuingTropicalCycloneAdvisoryCentre!= null);
    }

    /**
     * Gets the value of the tropicalCycloneName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTropicalCycloneName() {
        return tropicalCycloneName;
    }

    /**
     * Sets the value of the tropicalCycloneName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTropicalCycloneName(String value) {
        this.tropicalCycloneName = value;
    }

    public boolean isSetTropicalCycloneName() {
        return (this.tropicalCycloneName!= null);
    }

    /**
     * Gets the value of the advisoryNumber property.
     * 
     */
    public int getAdvisoryNumber() {
        return advisoryNumber;
    }

    /**
     * Sets the value of the advisoryNumber property.
     * 
     */
    public void setAdvisoryNumber(int value) {
        this.advisoryNumber = value;
    }

    public boolean isSetAdvisoryNumber() {
        return true;
    }

    /**
     * Gets the value of the observation property.
     * 
     * @return
     *     possible object is
     *     {@link OMObservationPropertyType }
     *     
     */
    public OMObservationPropertyType getObservation() {
        return observation;
    }

    /**
     * Sets the value of the observation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OMObservationPropertyType }
     *     
     */
    public void setObservation(OMObservationPropertyType value) {
        this.observation = value;
    }

    public boolean isSetObservation() {
        return (this.observation!= null);
    }

    /**
     * Gets the value of the forecast property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the forecast property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForecast().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OMObservationPropertyType }
     * 
     * 
     */
    public List<OMObservationPropertyType> getForecast() {
        if (forecast == null) {
            forecast = new ArrayList<OMObservationPropertyType>();
        }
        return this.forecast;
    }

    public boolean isSetForecast() {
        return ((this.forecast!= null)&&(!this.forecast.isEmpty()));
    }

    public void unsetForecast() {
        this.forecast = null;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    public boolean isSetRemarks() {
        return (this.remarks!= null);
    }

    /**
     * Gets the value of the expectedNextAdvisoryTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeInstantPropertyType }
     *     
     */
    public TimeInstantPropertyType getExpectedNextAdvisoryTime() {
        return expectedNextAdvisoryTime;
    }

    /**
     * Sets the value of the expectedNextAdvisoryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeInstantPropertyType }
     *     
     */
    public void setExpectedNextAdvisoryTime(TimeInstantPropertyType value) {
        this.expectedNextAdvisoryTime = value;
    }

    public boolean isSetExpectedNextAdvisoryTime() {
        return (this.expectedNextAdvisoryTime!= null);
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getExtension() {
        if (extension == null) {
            extension = new ArrayList<Object>();
        }
        return this.extension;
    }

    public boolean isSetExtension() {
        return ((this.extension!= null)&&(!this.extension.isEmpty()));
    }

    public void unsetExtension() {
        this.extension = null;
    }

}
