//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.06 at 11:11:25 PM MSK 
//


package schemabindings31._int.icao.iwxxm._3;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import schemabindings31.net.opengis.gml.v_3_2_1.AbstractGMLType;
import schemabindings31.net.opengis.gml.v_3_2_1.LengthType;
import schemabindings31.net.opengis.gml.v_3_2_1.TimePeriodPropertyType;


/**
 * <p>Java class for MeteorologicalAerodromeForecastType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeteorologicalAerodromeForecastType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractGMLType">
 *       &lt;sequence>
 *         &lt;element name="phenomenonTime" type="{http://www.opengis.net/gml/3.2}TimePeriodPropertyType"/>
 *         &lt;element name="prevailingVisibility" type="{http://www.opengis.net/gml/3.2}LengthType" minOccurs="0"/>
 *         &lt;element name="prevailingVisibilityOperator" type="{http://icao.int/iwxxm/3.0}RelationalOperatorType" minOccurs="0"/>
 *         &lt;element name="surfaceWind" type="{http://icao.int/iwxxm/3.0}AerodromeSurfaceWindForecastPropertyType" minOccurs="0"/>
 *         &lt;element name="weather" type="{http://icao.int/iwxxm/3.0}AerodromeForecastWeatherType" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="cloud" type="{http://icao.int/iwxxm/3.0}AerodromeCloudForecastPropertyType" minOccurs="0"/>
 *         &lt;element name="temperature" type="{http://icao.int/iwxxm/3.0}AerodromeAirTemperatureForecastPropertyType" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="extension" type="{http://icao.int/iwxxm/3.0}ExtensionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="changeIndicator" type="{http://icao.int/iwxxm/3.0}AerodromeForecastChangeIndicatorType" />
 *       &lt;attribute name="cloudAndVisibilityOK" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeteorologicalAerodromeForecastType", propOrder = {
    "phenomenonTime",
    "prevailingVisibility",
    "prevailingVisibilityOperator",
    "surfaceWind",
    "weather",
    "cloud",
    "temperature",
    "extension"
})
public class MeteorologicalAerodromeForecastType
    extends AbstractGMLType
{

    @XmlElement(required = true)
    protected TimePeriodPropertyType phenomenonTime;
    protected LengthType prevailingVisibility;
    @XmlSchemaType(name = "string")
    protected RelationalOperatorType prevailingVisibilityOperator;
    protected AerodromeSurfaceWindForecastPropertyType surfaceWind;
    protected List<AerodromeForecastWeatherType> weather;
    protected AerodromeCloudForecastPropertyType cloud;
    protected List<AerodromeAirTemperatureForecastPropertyType> temperature;
    protected List<ExtensionType> extension;
    @XmlAttribute(name = "changeIndicator")
    protected AerodromeForecastChangeIndicatorType changeIndicator;
    @XmlAttribute(name = "cloudAndVisibilityOK", required = true)
    protected boolean cloudAndVisibilityOK;

    /**
     * Gets the value of the phenomenonTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimePeriodPropertyType }
     *     
     */
    public TimePeriodPropertyType getPhenomenonTime() {
        return phenomenonTime;
    }

    /**
     * Sets the value of the phenomenonTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimePeriodPropertyType }
     *     
     */
    public void setPhenomenonTime(TimePeriodPropertyType value) {
        this.phenomenonTime = value;
    }

    public boolean isSetPhenomenonTime() {
        return (this.phenomenonTime!= null);
    }

    /**
     * Gets the value of the prevailingVisibility property.
     * 
     * @return
     *     possible object is
     *     {@link LengthType }
     *     
     */
    public LengthType getPrevailingVisibility() {
        return prevailingVisibility;
    }

    /**
     * Sets the value of the prevailingVisibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthType }
     *     
     */
    public void setPrevailingVisibility(LengthType value) {
        this.prevailingVisibility = value;
    }

    public boolean isSetPrevailingVisibility() {
        return (this.prevailingVisibility!= null);
    }

    /**
     * Gets the value of the prevailingVisibilityOperator property.
     * 
     * @return
     *     possible object is
     *     {@link RelationalOperatorType }
     *     
     */
    public RelationalOperatorType getPrevailingVisibilityOperator() {
        return prevailingVisibilityOperator;
    }

    /**
     * Sets the value of the prevailingVisibilityOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationalOperatorType }
     *     
     */
    public void setPrevailingVisibilityOperator(RelationalOperatorType value) {
        this.prevailingVisibilityOperator = value;
    }

    public boolean isSetPrevailingVisibilityOperator() {
        return (this.prevailingVisibilityOperator!= null);
    }

    /**
     * Gets the value of the surfaceWind property.
     * 
     * @return
     *     possible object is
     *     {@link AerodromeSurfaceWindForecastPropertyType }
     *     
     */
    public AerodromeSurfaceWindForecastPropertyType getSurfaceWind() {
        return surfaceWind;
    }

    /**
     * Sets the value of the surfaceWind property.
     * 
     * @param value
     *     allowed object is
     *     {@link AerodromeSurfaceWindForecastPropertyType }
     *     
     */
    public void setSurfaceWind(AerodromeSurfaceWindForecastPropertyType value) {
        this.surfaceWind = value;
    }

    public boolean isSetSurfaceWind() {
        return (this.surfaceWind!= null);
    }

    /**
     * Gets the value of the weather property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the weather property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWeather().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AerodromeForecastWeatherType }
     * 
     * 
     */
    public List<AerodromeForecastWeatherType> getWeather() {
        if (weather == null) {
            weather = new ArrayList<AerodromeForecastWeatherType>();
        }
        return this.weather;
    }

    public boolean isSetWeather() {
        return ((this.weather!= null)&&(!this.weather.isEmpty()));
    }

    public void unsetWeather() {
        this.weather = null;
    }

    /**
     * Gets the value of the cloud property.
     * 
     * @return
     *     possible object is
     *     {@link AerodromeCloudForecastPropertyType }
     *     
     */
    public AerodromeCloudForecastPropertyType getCloud() {
        return cloud;
    }

    /**
     * Sets the value of the cloud property.
     * 
     * @param value
     *     allowed object is
     *     {@link AerodromeCloudForecastPropertyType }
     *     
     */
    public void setCloud(AerodromeCloudForecastPropertyType value) {
        this.cloud = value;
    }

    public boolean isSetCloud() {
        return (this.cloud!= null);
    }

    /**
     * Gets the value of the temperature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the temperature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemperature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AerodromeAirTemperatureForecastPropertyType }
     * 
     * 
     */
    public List<AerodromeAirTemperatureForecastPropertyType> getTemperature() {
        if (temperature == null) {
            temperature = new ArrayList<AerodromeAirTemperatureForecastPropertyType>();
        }
        return this.temperature;
    }

    public boolean isSetTemperature() {
        return ((this.temperature!= null)&&(!this.temperature.isEmpty()));
    }

    public void unsetTemperature() {
        this.temperature = null;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionType }
     * 
     * 
     */
    public List<ExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<ExtensionType>();
        }
        return this.extension;
    }

    public boolean isSetExtension() {
        return ((this.extension!= null)&&(!this.extension.isEmpty()));
    }

    public void unsetExtension() {
        this.extension = null;
    }

    /**
     * Gets the value of the changeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link AerodromeForecastChangeIndicatorType }
     *     
     */
    public AerodromeForecastChangeIndicatorType getChangeIndicator() {
        return changeIndicator;
    }

    /**
     * Sets the value of the changeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link AerodromeForecastChangeIndicatorType }
     *     
     */
    public void setChangeIndicator(AerodromeForecastChangeIndicatorType value) {
        this.changeIndicator = value;
    }

    public boolean isSetChangeIndicator() {
        return (this.changeIndicator!= null);
    }

    /**
     * Gets the value of the cloudAndVisibilityOK property.
     * 
     */
    public boolean isCloudAndVisibilityOK() {
        return cloudAndVisibilityOK;
    }

    /**
     * Sets the value of the cloudAndVisibilityOK property.
     * 
     */
    public void setCloudAndVisibilityOK(boolean value) {
        this.cloudAndVisibilityOK = value;
    }

    public boolean isSetCloudAndVisibilityOK() {
        return true;
    }

}
