//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.06 at 11:11:25 PM MSK 
//


package schemabindings31._int.icao.iwxxm._3;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import schemabindings31.net.opengis.gml.v_3_2_1.AbstractFeatureType;


/**
 * <p>Java class for VolcanicAshForecastConditionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VolcanicAshForecastConditionsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractFeatureType">
 *       &lt;sequence>
 *         &lt;element name="phenomenonTime" type="{http://icao.int/iwxxm/3.0}AbstractTimeObjectPropertyType"/>
 *         &lt;element name="ashCloud" type="{http://icao.int/iwxxm/3.0}VolcanicAshCloudForecastPropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="extension" type="{http://icao.int/iwxxm/3.0}ExtensionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="status" use="required" type="{http://icao.int/iwxxm/3.0}VolcanicAshCloudForecastStatusType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VolcanicAshForecastConditionsType", propOrder = {
    "phenomenonTime",
    "ashCloud",
    "extension"
})
public class VolcanicAshForecastConditionsType
    extends AbstractFeatureType
{

    @XmlElement(required = true)
    protected AbstractTimeObjectPropertyType phenomenonTime;
    @XmlElement(nillable = true)
    protected List<VolcanicAshCloudForecastPropertyType> ashCloud;
    protected List<ExtensionType> extension;
    @XmlAttribute(name = "status", required = true)
    protected VolcanicAshCloudForecastStatusType status;

    /**
     * Gets the value of the phenomenonTime property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractTimeObjectPropertyType }
     *     
     */
    public AbstractTimeObjectPropertyType getPhenomenonTime() {
        return phenomenonTime;
    }

    /**
     * Sets the value of the phenomenonTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractTimeObjectPropertyType }
     *     
     */
    public void setPhenomenonTime(AbstractTimeObjectPropertyType value) {
        this.phenomenonTime = value;
    }

    public boolean isSetPhenomenonTime() {
        return (this.phenomenonTime!= null);
    }

    /**
     * Gets the value of the ashCloud property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ashCloud property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAshCloud().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VolcanicAshCloudForecastPropertyType }
     * 
     * 
     */
    public List<VolcanicAshCloudForecastPropertyType> getAshCloud() {
        if (ashCloud == null) {
            ashCloud = new ArrayList<VolcanicAshCloudForecastPropertyType>();
        }
        return this.ashCloud;
    }

    public boolean isSetAshCloud() {
        return ((this.ashCloud!= null)&&(!this.ashCloud.isEmpty()));
    }

    public void unsetAshCloud() {
        this.ashCloud = null;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionType }
     * 
     * 
     */
    public List<ExtensionType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<ExtensionType>();
        }
        return this.extension;
    }

    public boolean isSetExtension() {
        return ((this.extension!= null)&&(!this.extension.isEmpty()));
    }

    public void unsetExtension() {
        this.extension = null;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link VolcanicAshCloudForecastStatusType }
     *     
     */
    public VolcanicAshCloudForecastStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolcanicAshCloudForecastStatusType }
     *     
     */
    public void setStatus(VolcanicAshCloudForecastStatusType value) {
        this.status = value;
    }

    public boolean isSetStatus() {
        return (this.status!= null);
    }

}
