//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.18 at 02:04:43 PM MSK 
//


package _int.icao.iwxxm._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import net.opengis.gml.v_3_2_1.AbstractGMLType;
import net.opengis.gml.v_3_2_1.LengthType;


/**
 * <p>Java class for MeteorologicalAerodromeTrendForecastRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeteorologicalAerodromeTrendForecastRecordType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractGMLType">
 *       &lt;sequence>
 *         &lt;element name="prevailingVisibility" type="{http://www.opengis.net/gml/3.2}LengthType" minOccurs="0"/>
 *         &lt;element name="prevailingVisibilityOperator" type="{http://icao.int/iwxxm/2.0}RelationalOperatorType" minOccurs="0"/>
 *         &lt;element name="surfaceWind" type="{http://icao.int/iwxxm/2.0}AerodromeSurfaceWindTrendForecastPropertyType" minOccurs="0"/>
 *         &lt;element name="forecastWeather" type="{http://icao.int/iwxxm/2.0}AerodromeForecastWeatherType" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="cloud" type="{http://icao.int/iwxxm/2.0}AerodromeCloudForecastPropertyType" minOccurs="0"/>
 *         &lt;element name="extension" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="changeIndicator" use="required" type="{http://icao.int/iwxxm/2.0}ForecastChangeIndicatorType" />
 *       &lt;attribute name="cloudAndVisibilityOK" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeteorologicalAerodromeTrendForecastRecordType", propOrder = {
    "prevailingVisibility",
    "prevailingVisibilityOperator",
    "surfaceWind",
    "forecastWeather",
    "cloud",
    "extension"
})
public class MeteorologicalAerodromeTrendForecastRecordType
    extends AbstractGMLType
{

    protected LengthType prevailingVisibility;
    protected RelationalOperatorType prevailingVisibilityOperator;
    protected AerodromeSurfaceWindTrendForecastPropertyType surfaceWind;
    protected List<AerodromeForecastWeatherType> forecastWeather;
    protected AerodromeCloudForecastPropertyType cloud;
    protected List<Object> extension;
    @XmlAttribute(name = "changeIndicator", required = true)
    protected ForecastChangeIndicatorType changeIndicator;
    @XmlAttribute(name = "cloudAndVisibilityOK")
    protected Boolean cloudAndVisibilityOK;

    /**
     * Gets the value of the prevailingVisibility property.
     * 
     * @return
     *     possible object is
     *     {@link LengthType }
     *     
     */
    public LengthType getPrevailingVisibility() {
        return prevailingVisibility;
    }

    /**
     * Sets the value of the prevailingVisibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthType }
     *     
     */
    public void setPrevailingVisibility(LengthType value) {
        this.prevailingVisibility = value;
    }

    public boolean isSetPrevailingVisibility() {
        return (this.prevailingVisibility!= null);
    }

    /**
     * Gets the value of the prevailingVisibilityOperator property.
     * 
     * @return
     *     possible object is
     *     {@link RelationalOperatorType }
     *     
     */
    public RelationalOperatorType getPrevailingVisibilityOperator() {
        return prevailingVisibilityOperator;
    }

    /**
     * Sets the value of the prevailingVisibilityOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationalOperatorType }
     *     
     */
    public void setPrevailingVisibilityOperator(RelationalOperatorType value) {
        this.prevailingVisibilityOperator = value;
    }

    public boolean isSetPrevailingVisibilityOperator() {
        return (this.prevailingVisibilityOperator!= null);
    }

    /**
     * Gets the value of the surfaceWind property.
     * 
     * @return
     *     possible object is
     *     {@link AerodromeSurfaceWindTrendForecastPropertyType }
     *     
     */
    public AerodromeSurfaceWindTrendForecastPropertyType getSurfaceWind() {
        return surfaceWind;
    }

    /**
     * Sets the value of the surfaceWind property.
     * 
     * @param value
     *     allowed object is
     *     {@link AerodromeSurfaceWindTrendForecastPropertyType }
     *     
     */
    public void setSurfaceWind(AerodromeSurfaceWindTrendForecastPropertyType value) {
        this.surfaceWind = value;
    }

    public boolean isSetSurfaceWind() {
        return (this.surfaceWind!= null);
    }

    /**
     * Gets the value of the forecastWeather property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the forecastWeather property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForecastWeather().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AerodromeForecastWeatherType }
     * 
     * 
     */
    public List<AerodromeForecastWeatherType> getForecastWeather() {
        if (forecastWeather == null) {
            forecastWeather = new ArrayList<AerodromeForecastWeatherType>();
        }
        return this.forecastWeather;
    }

    public boolean isSetForecastWeather() {
        return ((this.forecastWeather!= null)&&(!this.forecastWeather.isEmpty()));
    }

    public void unsetForecastWeather() {
        this.forecastWeather = null;
    }

    /**
     * Gets the value of the cloud property.
     * 
     * @return
     *     possible object is
     *     {@link AerodromeCloudForecastPropertyType }
     *     
     */
    public AerodromeCloudForecastPropertyType getCloud() {
        return cloud;
    }

    /**
     * Sets the value of the cloud property.
     * 
     * @param value
     *     allowed object is
     *     {@link AerodromeCloudForecastPropertyType }
     *     
     */
    public void setCloud(AerodromeCloudForecastPropertyType value) {
        this.cloud = value;
    }

    public boolean isSetCloud() {
        return (this.cloud!= null);
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getExtension() {
        if (extension == null) {
            extension = new ArrayList<Object>();
        }
        return this.extension;
    }

    public boolean isSetExtension() {
        return ((this.extension!= null)&&(!this.extension.isEmpty()));
    }

    public void unsetExtension() {
        this.extension = null;
    }

    /**
     * Gets the value of the changeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link ForecastChangeIndicatorType }
     *     
     */
    public ForecastChangeIndicatorType getChangeIndicator() {
        return changeIndicator;
    }

    /**
     * Sets the value of the changeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForecastChangeIndicatorType }
     *     
     */
    public void setChangeIndicator(ForecastChangeIndicatorType value) {
        this.changeIndicator = value;
    }

    public boolean isSetChangeIndicator() {
        return (this.changeIndicator!= null);
    }

    /**
     * Gets the value of the cloudAndVisibilityOK property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCloudAndVisibilityOK() {
        return cloudAndVisibilityOK;
    }

    /**
     * Sets the value of the cloudAndVisibilityOK property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCloudAndVisibilityOK(boolean value) {
        this.cloudAndVisibilityOK = value;
    }

    public boolean isSetCloudAndVisibilityOK() {
        return (this.cloudAndVisibilityOK!= null);
    }

    public void unsetCloudAndVisibilityOK() {
        this.cloudAndVisibilityOK = null;
    }

}
