//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.06 at 11:11:25 PM MSK 
//


package schemabindings31.aero.aixm.schema._5_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractPropertiesWithScheduleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractPropertiesWithScheduleType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMObjectType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractPropertiesWithScheduleType")
@XmlSeeAlso({
    FlightConditionCombinationType.class,
    AirspaceActivationType.class,
    WorkareaActivityType.class,
    AltimeterSourceStatusType.class,
    VerticalStructureLightingStatusType.class,
    ProcedureAvailabilityType.class,
    NavaidEquipmentMonitoringType.class,
    SpecialNavigationStationStatusType.class,
    LightElementStatusType.class,
    UnitAvailabilityType.class,
    ServiceOperationalStatusType.class,
    GroundLightingAvailabilityType.class,
    AirportHeliportResponsibilityOrganisationType.class,
    ConditionCombinationType.class,
    ManoeuvringAreaAvailabilityType.class,
    TelephoneContactType.class,
    RadioCommunicationOperationalStatusType.class,
    NavaidOperationalStatusType.class,
    CirclingRestrictionType.class,
    PostalAddressType.class,
    OnlineContactType.class,
    RunwayDeclaredDistanceValueType.class,
    RouteAvailabilityType.class,
    AirportHeliportAvailabilityType.class,
    VerticalStructurePartType.class,
    ApronAreaAvailabilityType.class,
    AirspaceLayerClassType.class
})
public class AbstractPropertiesWithScheduleType
    extends AbstractAIXMObjectType
{


}
