//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.06 at 11:11:25 PM MSK 
//


package schemabindings31.aero.aixm.schema._5_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NavigationAreaSectorPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NavigationAreaSectorPropertyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMPropertyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.aixm.aero/schema/5.1.1}NavigationAreaSector"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NavigationAreaSectorPropertyType", propOrder = {
    "navigationAreaSector"
})
public class NavigationAreaSectorPropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElement(name = "NavigationAreaSector", required = true)
    protected NavigationAreaSectorType navigationAreaSector;

    /**
     * Gets the value of the navigationAreaSector property.
     * 
     * @return
     *     possible object is
     *     {@link NavigationAreaSectorType }
     *     
     */
    public NavigationAreaSectorType getNavigationAreaSector() {
        return navigationAreaSector;
    }

    /**
     * Sets the value of the navigationAreaSector property.
     * 
     * @param value
     *     allowed object is
     *     {@link NavigationAreaSectorType }
     *     
     */
    public void setNavigationAreaSector(NavigationAreaSectorType value) {
        this.navigationAreaSector = value;
    }

    public boolean isSetNavigationAreaSector() {
        return (this.navigationAreaSector!= null);
    }

}
